### ISSUE TITLE
feat(evm): support unknown t8n tools

### ISSUE THREAD

**Issue by winsvega** [ethereum/execution-spec-tests#311]
this is really a stopper. please treat any unknown t8n as default (geth) interface t8n.

```
INTERNALERROR> evm_transition_tool.transition_tool.UnknownTransitionTool: Unknown transition tool binary: /home/wins/.retesteth/pyt8n/start.sh
```

**Comment by danceratopz** [comment]
From  #328:
> I think it's a great idea to add the "file system" implementation of evaluate() from evmone into TransitionTool so that other tools can use it.
> 
> However, I would prefer to not have Geth as a default and instead insist that all t8n tools that should be used provide an interface. I don't think this is unreasonable, as the interface module is < 40 lines (see the evmone interface, in this, PR for example).
> 
> So while I'd like to keep _evaluate_stream() and _evaluate_filesystem(), I would prefer to add a separate interface for your custom t8n which must provide either a -v or --version flag which contains its name to make it identifiable.
> 
> The reason being, is that I'd like to avoid ambiguity about which features a t8n tools supports and which not, like tracing, for example. I'd prefer to have this explicit in the implementation and not stumble over bugs/inconsistencies because the tools are consistent.
> 
> Further reasoning, is that we still need to signal to GethTransitionTool which version of the evaluate function to use. Currently, in this implementation, it defaults to "filesystem" which changes the current behavior, which should stay as "stream", imo. To be entirely flexible with a "default" fallback tool, we'd have to add a command-line flag which defines whether to use "stream" or "filesystem", this clutters the interface; again, I'd prefer to keep it consistent.

**Comment by winsvega** [comment]
But this way new teams/clients will have to stop untill pyspec adds the integration. 

Actually there was supposed to be a protocol, not 10 different versions of t8n that need a support.

A strict protocol that once implemented can be used to generate and run the tests with testing tools.

**Comment by danceratopz** [comment]
Hi @winsvega, as we discussed (in the discussion from #328 and offline). We would prefer to keep the interfaces to t8n tools explicit in order to more quickly catch bugs.

There are a few other factors here to consider with regards to this decision:
1. An interface for a new tool can be added extremely quickly. The closer it is to the geth interface, the faster it is to add.
2. As far as I can tell, there is small and limited number of t8n tools to be added. This does not block lots of teams.
3. The `TransitionTool` class is growing beyond the scope of just being an interface to evm `t8n` tools, it now also interfaces to geth's `evm blocktest` command, which is certainly not offered by other clients in this form, see next point.
4. Whilst pursuing the standardization of evm commands, flags and input/outputs is extremely worthwhile, the fact is that their commands aren't and can't all be squeezed into exactly the same format. The largest example being the fact that we execute besu's t8n capability through it's `t8n-server` via REST instead of calling a standalone executable.
