### ISSUE TITLE
Add Spec Version to the Produced Fixtures

### ISSUE THREAD

**Issue by marioevz** [ethereum/execution-spec-tests#45]
At the moment it is impossible to know which commit (either of the [EIPs](https://github.com/ethereum/EIPs) repo or the [Execution Apis](https://github.com/ethereum/execution-apis/) repo) is the written test based on.

A great addition to the output fixture format would be the specific commit of these repos from which the tests were modeled after.

For example:
- https://github.com/ethereum/EIPs/tree/f26568d954d666af60930563d8469855b62a3f28
or
- https://github.com/ethereum/execution-apis/tree/b7c5d3420e00648f456744d121ffbd929862924d

or both.

This way everyone can easily identify that the tests are out of date.

**Comment by winsvega** [comment]
Speaking of versioning here is the info section
```
            "filling-rpc-server" : "evm version 1.10.20-unstable-ba99e192-20220616",
            "filling-tool-version" : "retesteth-0.2.2-testinfo+commit.e48b58bc.Linux.g++",
            "generatedTestHash" : "648a4f2707dfd4c4eb4c70ef78931fa8e9d82429c777ff8a70b8d7ff4c58aefa",
            "lllcversion" : "Version: 0.5.14-develop.2022.6.16+commit.401d5358.Linux.g++",
            "solidity" : "Version: 0.8.5+commit.a4f2e591.Linux.g++",
            "source" : "src/BlockchainTestsFiller/ValidBlocks/bcEIP3675/tipInsideBlockFiller.yml",
            "sourceHash" : "ec69209b98c76673d794939765efff731b1f57400bf6fb3c8c37a325a7d33bfb"
```

`filling-rpc-server`  refers to evm t8n version. rpc server because there was an idea to ask remote evm providers for test execution using rpc test protocol, not t8n. 

`filling-tool-version` is pyspec version

`source` is relative path from the test repo to .py script that generated the test. 

`sourceHash`  is the hash of the script. in case we edit the test src it will be visible that the test need regeneration. 

`generatedTestHash`  is the hash of the generated test json without the _info section. printed as string with spaces stripped. used to verify if the test regeneration changed the existing test or not. if not, then _info section is not updated when regenerating all the tests.
