### ISSUE TITLE
Feature request: forknames, chainid as options

### ISSUE THREAD

**Issue by winsvega** [ethereum/execution-spec-tests#57]
We have ETC classic team who need this feature. They use different forknames and chainid. 
would be nice to have a config file options that specify following:

- t8n tool to use (path or smth)
- chainid to generate transactions with. 
- forknames map (testName -> actualName that is sent to t8n)

or support it as cmd options when running the test generation. 
this is a request feature low priority.

**Comment by danceratopz** [comment]
This would require a separate implementation of the `ethereum_test_forks` package in order to add the required logic for each fork and adding an interface to select which implementation to use. We discussed internally and decided this is not something we'll add to this repo, but anyone is welcome to fork and add the required logic for their chain.
